[project]
name = "paddleocr"
version = "0.1.0"
requires-python = "=3.10"
dependencies = [
    "opencv-python>=4.13.0.92",
    "opencv-stubs>=0.1.2",
    "paddlepaddle-gpu>=3.3.0",
    "paddleocr",
]

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120
known_third_party = ["PIL", "paddleocr"]
skip_gitignore = true
combine_as_imports = true
include_trailing_comma = true
multi_line_output = 3

[tool.pylint.main]
ignore = ["CVS", "__pycache__", ".venv", "venv", "build", "dist"]
# source-roots = ["."]

[tool.pylint.format]
max-line-length = 120     # Black/isort alignement

[tool.pylint.MASTER]
extension-pkg-allow-list = ["cv2"]

[tool.pylint."TYPECHECK"]
generated-members = ["cv2.*"]

[tool.pylint."REPORTS"]
score = "no"

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "R0903"   # too-few-public-methods
]
# Ensure that the unused import warning is enabled (W0611)
enable = ["unused-import"]

[tool.pylint.basic]
# Prevent "invalid-name" on short names (C0103)
good-names = [
  "i", "j", "k", "_",     # counters/tokens
  "id", "pk", "db",       # id and database
  "fn", "fp",             # filename / filepath
  "ex",                   # exception alias
  "ts", "dt"              # timestamps / datetime
]
